FROM rackattack-nas.dc1:5000/ubuntu-dev-base:379308aa77bd0a19ebf12d868e7d19ee35a19d6c
RUN apt-get install -y python2.7 python2.7-dev
RUN curl 'https://bootstrap.pypa.io/pip/2.7/get-pip.py' | python2.7
COPY requirements.txt /tmp/requirements.txt
COPY dev-requirements.txt /tmp/dev-requirements.txt
RUN python2.7 -m pip install -r /tmp/requirements.txt -r /tmp/dev-requirements.txt
RUN python3 -m pip install -r /tmp/requirements.txt -r /tmp/dev-requirements.txt
RUN rm /tmp/requirements.txt /tmp/dev-requirements.txt
